config/routes.rb
Rails.application.routes.draw do
  resource :leads, only: [:new, :create]
  resources :posts
  devise_for :users
  root to: 'posts#index'


  get '/startexperience', to: 'pages#startexperience', as: 'startexperience'
  get '/conteudo_extra', to: 'pages#content', as: 'content'
  get '/show_me_the_leads', to: 'leads#index', as: 'show_me_the_leads'
  get '/politica_privacidade', to: 'pages#privacy_policy', as: 'privacy_policy'
  get '/:id' , to: 'posts#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lead.rb
class Lead < ApplicationRecord
	validates :name, presence: { message: "O Nome é obrigatório" }
	validates :last_name, presence: { message: "O Sobrenome é obrigatório" } 
	validates :email, presence: true, uniqueness: { message: "Esse e-mail já foi cadastrado" }, format: { with: URI::MailTo::EMAIL_REGEXP, message: " com formato inválido" }

	def self.to_csv
	    attributes = %w{id name last_name email ip created_at}

	    CSV.generate(headers: true) do |csv|
	      csv << attributes

	      all.each do |lead|
	        csv << attributes.map{ |attr| lead.send(attr) }
	      end
	    end
	  end
end

app/models/post.rb
class Post < ApplicationRecord
	mount_uploader :image, ImageUploader
	extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["HOST"] || "localhost:3000" }
  end
  
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :set_lead, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:create, :new]

  def index
    @leads = Lead.all

    respond_to do |format|
      format.html
      format.csv { send_data @leads.to_csv, filename: "leads-#{Date.today}.csv" }
    end
  end

  # GET /leads/1
  # GET /leads/1.json
  def show
  end

  # GET /leads/new
  def new
    @lead = Lead.new
  end


  # POST /leads
  # POST /leads.json
  def create
    @lead = Lead.new(lead_params)
    @lead.ip = request.remote_ip
    respond_to do |format|
      if @lead.save
        firebase = Firebase::Client.new(ENV['FIREBASE_URL'], ENV['FIREBASE_SECRET'])
        response = firebase.push("leads", { id: @lead.id, name: @lead.name, last_name: @lead.last_name, email: @lead.email, ip: @lead.ip, created_at: @lead.created_at.to_s })
        format.html { redirect_to content_path, notice: 'Parabéns! Esse é nosso conteúdo exclusivo.' }
      else
        if Lead.where(email:@lead.email).exists?
          format.html { redirect_to content_path, notice: 'Esse email já está cadastrado!' }
        else
          format.html { render :new }
        end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lead
      @lead = Lead.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lead_params
      params.require(:lead).permit(:name, :last_name, :email, :ip)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :content, :privacy_policy, :startexperience]
  def home
  end

  def content
  end

  def privacy_policy
  end

  def startexperience
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @lead = Lead.new
  end


  # GET /posts/1
  # GET /posts/1.json
  def show
    @lead = Lead.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Artigo criado com sucesso!' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Artigo atualizado!' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Artigo apagado!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :body, :keywords, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_keywords
    content_for?(:meta_keywords) ? content_for(:meta_keywords) : DEFAULT_META["meta_keywords"]
  end

  def meta_image
      meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
      # little twist to make it work equally with an asset or a url
      meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
    end

end

app/views/active_storage/blobs/_blob.html.erb
<% transformations = { resize: local_assigns[:in_gallery] ? "800x600>" : "1024x768>" } %>
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.variable? %>
    <%= image_tag blob.variant(transformations) %>
  <% elsif blob.previewable? %>
    <%= image_tag blob.preview(transformations) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:url" content="https://www.deostart.com.br">
    <meta name="description" content="<%= meta_description %>">
    <meta name="keywords" content="<%= meta_keywords %>"/>
    <title>Dê o START</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= favicon_link_tag 'logo.ico'  %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' unless request.path_info.include?('/startexperience') %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= render 'shared/footer'  unless request.path_info.include?('/startexperience') %>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-126900873-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-126900873-1');
    </script>

  </body>
</html>

app/views/leads/_form.html.erb
<%= simple_form_for(@lead) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name, label:"Nome" %>
    <%= f.input :last_name, label:"Sobrenome" %>
    <%= f.input :email, label:"E-mail" %>
    <% f.input :ip %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Acessar Conteúdo", class:"btn btn-success" %>
  </div>
<% end %>

app/views/leads/edit.html.erb
<h1>Editing Lead</h1>

<%= render 'form', lead: @lead %>

<%= link_to 'Show', @lead %> |
<%= link_to 'Back', leads_path %>

app/views/leads/index.html.erb
<div class="container-fluid">
  <div class="row d-flex justify-content-center">
    <div class="col-sm-10">
      <div class="card">
        <div class="card-body">
          <p><h1>We have: <%= @leads.all.count %> leads</h1></p>
          <%= link_to 'Download CSV', show_me_the_leads_path(format: :csv), class: "btn btn-success" %>
          <br>
          <br>
          <table>
            <thead>
              <tr>
                <th>Name</th>
                <th> | </th>
                <th>Last Name</th>
                <td> | </td>
                <th>Email</th>
                <td> | </td>
                <th>Ip</th>
                <td> | </td>
                <th>Time</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @leads.each do |lead| %>
                <tr>
                  <td><%= lead.name %></td>
                  <td> | </td>
                  <td><%= lead.last_name %></td>
                  <td> | </td>
                  <td><%= lead.email %></td>
                  <td> | </td>
                  <td><%= lead.ip %></td>
                  <td> | </td>
                  <td><%= lead.created_at %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/leads/new.html.erb
<div class="container-fluid">
  <div class="row d-flex justify-content-center">
    <div class="col-sm-6">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title">Preencha seus dados corretamente</h2>
          <%= render 'form', lead: @lead %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/leads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lead.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @lead.email %>
</p>

<p>
  <strong>Ip:</strong>
  <%= @lead.ip %>
</p>

<%= link_to 'Edit', edit_lead_path(@lead) %> |
<%= link_to 'Back', leads_path %>

app/views/pages/content.html.erb
<div class="container-fluid leads">
  <div class="row d-flex justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title">Conteúdo Extra</h2>
          <ul class="card-text">
            <li><%= link_to "Como cadastrar no Simple Nacional", asset_path("INFO_SIMPLESNACIONAL.pdf"), :class => "links", target: '_blank' %></li>
            <li><%= link_to "EBOOK: Guia para emitir Nota Fiscal", asset_path("GUIA_PARA_EMITIR_NOTA_FISCAL_EBOOK.pdf"), :class => "links", target: '_blank' %></li>
            <li><%= link_to "Dê o start em novos hábitos", asset_path("De_o_start_em_novos_habitos.pdf"), :class => "links", target: '_blank' %></li>
            <li><%= link_to "Planilha Gantt", asset_path("Planilha Gantt.xlsx"), :class => "links", target: '_blank' %></li>
            <li><%= link_to "Financiamento Descomplicado", asset_path("financiamento_descomplicado.png"), :class => "links", target: '_blank' %></li>
            <li><%= link_to "Guia Basico De Investimento", asset_path("guia_basico_de_investimento.png"), :class => "links", target: '_blank' %></li>
      			<li><%= link_to "Infográfico: Como se cadastrar no Simples Nacional", asset_path("Infografico_como_se_cadastrar_no_Simples_Nacional.pdf"), :class => "links", target: '_blank' %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/privacy_policy.html.erb
<div class="container policy">
	<div class="card">
	  <div class="card-body">
	    <h3 class="card-title">Política de Privacidade</h3>
	    

	    <p><span style="font-size:16px;"><strong>SEÇÃO 1 - O QUE FAREMOS COM ESTA INFORMAÇÃO?</strong></span></p>

	    <p>Quando você realiza alguma transação com nossa loja, como parte do processo de compra e venda, coletamos as informações pessoais que você nos dá tais como: nome, e-mail e endereço.</p>

	    <p>Quando você acessa nosso site, também recebemos automaticamente o protocolo de internet do seu computador, endereço de IP, a fim de obter informações que nos ajudam a aprender sobre seu navegador e sistema operacional.</p>

	    <p>Email Marketing será realizado apenas caso você permita. Nestes emails você poderá receber notícia sobre nossa loja, novos produtos e outras atualizações.</p>

	    <p><span style="font-size:16px;"><strong>SEÇÃO 2 - CONSENTIMENTO</strong></span></p>

	    <p>Como vocês obtêm meu consentimento?</p>

	    <p>Quando você fornece informações pessoais como nome, telefone e endereço, para completar: uma transação, verificar seu cartão de crédito, fazer um pedido, providenciar uma entrega ou retornar uma compra. Após a realização de ações entendemos que você está de acordo com a coleta de dados para serem utilizados pela nossa empresa.</p>

	    <p>Se pedimos por suas informações pessoais por uma razão secundária, como marketing, vamos lhe pedir diretamente por seu consentimento, ou lhe fornecer a oportunidade de dizer não.</p>

	    <p>E caso você queira retirar seu consentimento, como proceder?</p>

	    <p>Se após você nos fornecer seus dados, você mudar de ideia, você pode retirar o seu consentimento para que possamos entrar em contato, para a coleção de dados contínua, uso ou divulgação de suas informações, a qualquer momento, entrando em contato conosco em equipezerinho@gmail.com ou nos enviando uma correspondência em: Dê o Start www.deostart.com.br</p>

	    <p><strong><span style="font-size:16px;">SEÇÃO 3 - DIVULGAÇÃO</span></strong></p>

	    <p>Podemos divulgar suas informações pessoais caso sejamos obrigados pela lei para fazê-lo ou se você violar nossos Termos de Serviço.</p>

	    <p><span style="font-size:16px;"><strong>SEÇÃO 4 - SERVIÇOS DE TERCEIROS</strong></span></p>

	    <p>No geral, os fornecedores terceirizados usados por nós irão apenas coletar, usar e divulgar suas informações na medida do necessário para permitir que eles realizem os serviços que eles nos fornecem.</p>

	    <p>Entretanto, certos fornecedores de serviços terceirizados, tais como gateways de pagamento e outros processadores de transação de pagamento, têm suas próprias políticas de privacidade com respeito à informação que somos obrigados a fornecer para eles de suas transações relacionadas com compras.</p>

	    <p>Para esses fornecedores, recomendamos que você leia suas políticas de privacidade para que você possa entender a maneira na qual suas informações pessoais serão usadas por esses fornecedores.</p>

	    <p>Em particular, lembre-se que certos fornecedores podem ser localizados em ou possuir instalações que são localizadas em jurisdições diferentes que você ou nós. Assim, se você quer continuar com uma transação que envolve os serviços de um fornecedor de serviço terceirizado, então suas informações podem tornar-se sujeitas às leis da(s) jurisdição(ões) nas quais o fornecedor de serviço ou suas instalações estão localizados.</p>

	    <p>Como um exemplo, se você está localizado no Canadá e sua transação é processada por um gateway</p>

	    <p>Uma vez que você deixe o site da nossa loja ou seja redirecionado para um aplicativo ou site de terceiros, você não será mais regido por essa Política de Privacidade ou pelos Termos de Serviço do nosso site.</p>

	    <p>Links</p>

	    <p>Quando você clica em links na nossa loja, eles podem lhe direcionar para fora do nosso site. Não somos responsáveis pelas práticas de privacidade de outros sites e lhe incentivamos a ler as declarações de privacidade deles.</p>

	    <p><span style="font-size:16px;"><strong>SEÇÃO 5 - SEGURANÇA</strong></span></p>

	    <p>Para proteger suas informações pessoais, tomamos precauções razoáveis e seguimos as melhores práticas da indústria para nos certificar que elas não serão perdidas inadequadamente, usurpadas, acessadas, divulgadas, alteradas ou destruídas.</p>

	    <p>Se você nos fornecer as suas informações de cartão de crédito, essa informação é criptografada usando tecnologia &quot;secure socket layer&quot; (SSL) e armazenada com uma criptografia AES-256. Embora nenhum método de transmissão pela Internet ou armazenamento eletrônico é 100% seguro, nós seguimos todos os requisitos da PCI-DSS e implementamos padrões adicionais geralmente aceitos pela indústria.</p>

	    <p><span style="font-size:16px;"><strong>SEÇÃO 6 - ALTERAÇÕES PARA ESSA POLÍTICA DE PRIVACIDADE</strong></span></p>

	    <p>Reservamos o direito de modificar essa política de privacidade a qualquer momento, então por favor, revise-a com frequência. Alterações e esclarecimentos vão surtir efeito imediatamente após sua publicação no site. Se fizermos alterações de materiais para essa política, iremos notificá-lo aqui que eles foram atualizados, para que você tenha ciência sobre quais informações coletamos, como as usamos, e sob que circunstâncias, se alguma, usamos e/ou divulgamos elas.</p>

	    <p>Se nossa loja for adquirida ou fundida com outra empresa, suas informações podem ser transferidas para os novos proprietários para que possamos continuar a vender produtos para você.</p>


	  </div>
	  <br><br>
      <p class="card-text d-flex justify-content-center"><%= link_to 'Voltar', posts_path, class: "btn btn-primary" %></p>
	</div>
</div>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :body, :as => :ckeditor, input_html: {ckeditor: {toolbar: 'Full'}} %>
    <%= f.input :keywords %>
    <%= f.input :image %>
    <%= cl_image_tag @post.image, height: 50 %>
    <%= f.input :image_cache, as: :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_leadform.html.erb
<%= simple_form_for(@lead) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name, label: "Nome" %>
    <%= f.input :last_name, label: "Sobrenome" %>
    <%= f.input :email, label: "E-mail" %>
    <% f.input :ip %>
  </div>

  <div class="form-actions align-self-center">
    <%= f.button :submit, "Acessar Conteúdo", class: "btn btn-success" %>
  </div>
<% end %>

app/views/posts/_markdown.html.erb
<%= m yield %>

app/views/posts/edit.html.erb
<div class="container-fluid">
  <div class="row d-flex justify-content-center">
    <div class="col-sm-10">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title">Editar Artigo</h2>
          <%= render 'form', post: @post %>
		  <br>
		  <br>
          <%= link_to 'Show', @post %> |
          <%= link_to 'Back', posts_path %>
          <br>
          <%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container-fluid">
  <div class="row d-flex justify-content-center">
    <div class="col-sm-10">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title">Novo Artigo</h2>
          <%= render 'form', post: @post %>
		  <br>
          <%= link_to 'Back', posts_path , class:"btn btn-secondary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<% content_for :meta_description, @post.description %>
<% content_for :meta_title, @post.title %>
<% content_for :meta_keywords, @post.keywords %>
<div class="container-fluid">
	<div class="card">
	  	<% if !@post.image.nil? %>
	  	  <%= cl_image_tag @post.image, height: 300, width: '100%', class: "card-img-top" %>
	  	<% else %>
	  	  <img class="card-img-top" src="https://picsum.photos/791/180/?random">
	  	<% end %>
	  <div class="card-body">
	    <div class="float-right">
	      <div class="fb-like" data-href="https://www.facebook.com/blogdeostart/" data-layout="button_count" data-action="like" data-size="large" data-show-faces="true" data-share="true"></div>
	    </div>
	    <h3 class="card-title"><%= @post.title %></h3>
	    <p class="card-text"><%= @post.body.html_safe %></p>
	    <p class="card-text"><small class="text-muted"><%= @post.keywords %></small></p>
	  </div>
	  <% if !user_signed_in? %>
	  
	  <% end %>
	  <% if user_signed_in? %>
	    <p class="card-text d-flex justify-content-center"><%= link_to 'Editar', edit_post_path(@post), class: "btn btn-secondary" %></p>
	    <br>
	    <p class="card-text d-flex justify-content-center"><%= link_to 'Apagar', @post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></p>
	  <% end %>
	  <br><br>
      <p class="card-text d-flex justify-content-center"><%= link_to 'Voltar', posts_path, class: "btn btn-primary" %></p>
	</div>
</div>

<div class="modal fade" id="leadmodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Deixe seu contato e acesse um conteúdo exclusivo</h5>
      </div>
      <div class="modal-body">
      	<%= render 'leadform', lead: @lead %>
      </div>
    </div>
  </div>
</div>


<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v3.1&appId=285065402108466&autoLogAppEvents=1';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small blue navbar sticky-bottom d-flex justify-content-center">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3 ">
  	<%= link_to "Nossa Política de Privacidade", privacy_policy_path %>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/shared/_navbar.html.erb
<div class="navbar-wagon fixed-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand navbar-wagon-link" do %>
    <%= image_tag "logo2.png" %> 
  <% end %>
  <div class="facebook">
    <%= link_to 'https://goo.gl/riQ4i5', class: "navbar-wagon-item navbar-wagon-link", target: '_blank' do %>
      <i class="fab fa-facebook-square fa-2x"> <w>Visite no Facebook</w></i>
    <% end %>
  </div>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right">

    <%= link_to image_tag("start-xp.png"), startexperience_path, class: "navbar-wagon-item navbar-wagon-link xp" %>
    <%= link_to "Artigos", root_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% link_to "Conteúdo EXCLUSIVO", content_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to t(".teste", default: "Novo Post"), new_post_path, class: "navbar-wagon-item navbar-wagon-link" %>
    
    <% if user_signed_in? %>

      <!-- Links when logged in -->

      <%= link_to "Show me the Leads", show_me_the_leads_path, class: "btn btn-danger navbar-wagon-item navbar-wagon-link" %>
      <%= link_to destroy_user_session_path, class: "navbar-wagon-item navbar-wagon-link", method: :delete do %>
        <%= t(".sign_out", default: "Sair") %>
      <% end %>
    <% else %>
      <!-- Login link (when logged out) -->
    <% end %>
    
  </div>
</div>